= PAPRa Docs

This repository contains the content and source code for generating the https://tetrabiodistributed.github.io/papra[PAPRa] site.

== Running the website locally

You can build and serve the documentation site on a local desktop:

Note: It is recommended you run the following instructions on a Linux/Unix-like operating system. If you are on a Windows machine, consider installing https://docs.microsoft.com/en-us/windows/wsl/install-win10[Windows Subsystem for Linux].

=== Installing requirements

You will need https://git-scm.com/[git] to clone the project contents and https://podman.io/getting-started/installation[podman] to run the podman image that contains the dependencies needed for building the documentation.

. https://git-scm.com/downloads[git].
. https://podman.io/getting-started/installation[podman].

=== Cloning the repo

Clone the https://github.com/tetrabiodistributed/papra[PAPRa repo]. Don't forget to use `--recurse-submodules` flag, or else you won't pull down some of the code you need to generate a working site.

[source,bash]
----
git clone --recurse-submodules https://github.com/tetrabiodistributed/papra.git
cd papra
----

Note: If you accidentally cloned without using `--recurse-submodules`, you can run `git submodule update --init --recursive` to pull down submodules needed to generate a working site.

=== Building the documentation

Once you've cloned the repo & installed podman, run the `build.sh` script in the project root directory. This will pull the podman images, as well as install node modules, needed for generating the `papra` page locally. You can view all locally installed podman images by running `podman images`.

[source,bash]
----
./build.sh
----

Run the `serve.sh` script in the site root directory. By default, your site will be available at `+http://localhost:1313/papra+`.

[source,bash]
----
./serve.sh
----

. Now that you're serving your site locally, Hugo will watch for changes to the content and automatically refresh your site.

== Licensing

image:./assets/oshw_cert_us002161.svg[OSHW Certification US002162, link="./assets/oshw_cert_us002161.svg"]

Code licensed link:LICENSE[MIT]

Docs licensed link:https://creativecommons.org/licenses/by/4.0/[CC BY 4.0]
